# Generated by Django 2.0.2 on 2018-02-25 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('genre', models.IntegerField(choices=[(1, 'Fiction'), (2, 'Biography & Memoirs'), (3, 'History'), (4, 'Motivational'), (5, 'Religious'), (6, 'Business & Economy'), (7, 'Dictionary'), (8, 'Specialty Books')])),
                ('appearance_date', models.DateField()),
                ('cover', models.ImageField(blank=True, default='', upload_to='')),
                ('authors', models.ManyToManyField(related_name='Books', to='booktifier.Author')),
                ('votes', models.ManyToManyField(blank=True, related_name='UserBook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
