# Generated by Django 2.0.2 on 2018-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0002_buser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
