# Generated by Django 2.0.2 on 2018-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0004_remove_buser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(default='ceva', max_length=200),
            preserve_default=False,
        ),
    ]
