# Generated by Django 2.0.2 on 2018-04-09 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktifier', '0005_book_publishing_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='CommentUserBook', to=settings.AUTH_USER_MODEL),
        ),
    ]
