# Generated by Django 2.0.2 on 2018-04-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0006_auto_20180409_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
    ]
