# Generated by Django 2.0.4 on 2018-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0009_auto_20180411_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='buser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
