# Generated by Django 2.0.4 on 2018-06-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0010_auto_20180510_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='author',
            name='sign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
