# Generated by Django 2.0.4 on 2018-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0013_auto_20180604_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Fiction'), (2, 'Biography & Memoirs'), (3, 'History'), (4, 'Motivational'), (5, 'Religious'), (6, 'Business & Economy'), (7, 'Dictionary'), (8, 'Specialty Books'), (9, 'Romance'), (10, 'Mystery')]),
        ),
    ]
