# Generated by Django 2.0.4 on 2018-09-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0017_auto_20180604_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buser',
            name='blocked',
        ),
    ]
