# Generated by Django 2.0.4 on 2018-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0018_remove_buser_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
