# Generated by Django 2.0.4 on 2018-09-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktifier', '0019_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
